[purelymail]
source   = maildir://~/.local/share/mail/purelymail
outgoing = smtps://julian@seemyvest.net@smtp.purelymail.com:465
outgoing-cred-cmd = pass personal/purelymail/app-password
from     = Julian Andrews <julian@seemyvest.net>
copy-to  = Sent
default  = Inbox
