[fastmail]
source   = notmuch://~/.local/share/mail/fastmail
maildir-store = ~/.local/share/mail/fastmail
multi-file-strategy = act-all
outgoing = smtps://julian@seemyvest.net@smtp.fastmail.com:465
outgoing-cred-cmd = pass personal/fastmail/app-password
from     = Julian Andrews <julian@seemyvest.net>
copy-to  = Sent
default  = Inbox
