[general]
use-terminal-pinentry = true
default-save-path=~/Downloads/
enable-osc8=true
default-menu-cmd=fzf

[ui]
styleset-name=tokyonight-storm
dirlist-tree=true
dirlist-collapse=1
fuzzy-complete=true
reverse-thread-order=true
threading-enabled=true

[statusline]

[viewer]
alternatives=text/html,text/plain

[compose]
address-book-cmd=khard email --remove-first-line --parsable %s
file-picker-cmd=find ~ -not -path '*/.*' | fzf --multi

[multipart-converters]

[filters]
text/plain=colorize
text/calendar=calendar
message/delivery-status=colorize
message/rfc822=colorize
text/html=! html-unsafe
.headers=colorize

[openers]

[hooks]
mail-added=[ "$AERC_FOLDER" = "Inbox" ] && folder=INBOX || folder=$AERC_FOLDER;systemctl --user start mbsync@purelymail:$folder:n
mail-deleted=[ "$AERC_FOLDER" = "Inbox" ] && folder=INBOX || folder=$AERC_FOLDER;systemctl --user start mbsync@purelymail:$folder:g
flag-changed=[ "$AERC_FOLDER" = "Inbox" ] && folder=INBOX || folder=$AERC_FOLDER;systemctl --user start mbsync@purelymail:$folder:f

[templates]
