[general]
use-terminal-pinentry = true
default-save-path=~/Downloads/
enable-osc8=true
default-menu-cmd=fzf

[ui]
styleset-name=tokyonight-storm
dirlist-tree=true
dirlist-collapse=1
fuzzy-complete=true
reverse-thread-order=true
threading-enabled=true

[statusline]

[viewer]
alternatives=text/html,text/plain

[compose]
address-book-cmd=khard email --remove-first-line --parsable %s
file-picker-cmd=find ~ -not -path '*/.*' | fzf --multi

[multipart-converters]

[filters]
text/plain=colorize
text/calendar=calendar
message/delivery-status=colorize
message/rfc822=colorize
text/html=! html-unsafe
.headers=colorize

[openers]

[hooks]
aerc-startup=systemctl --user start --no-block mbsync@fastmail.service
mail-added=systemctl --user start --no-block mbsync@fastmail.service
mail-deleted=systemctl --user start --no-block mbsync@fastmail.service
flag-changed=systemctl --user start --no-block mbsync@fastmail.service
aerc-shutdown=systemctl --user start --no-block mbsync@fastmail.service

[templates]
