template = "{{memory}} | {{cpu}} | {{jellyfin_status}}{{apt_status}}{{local_mail}} | {{gmail}} | {{volume}} | {{wireless}}{{ethernet}}"

[ blocks.cpu ]
kind = "cpu"
template = """<fn=2> </fn>
{%- if cpu_times.non_idle < 20 -%}
    {%- set color="#586e75" -%}
{%- elif cpu_times.non_idle > 50 -%}
    {%- set color="#dc322f" -%}
{%- else -%}
    {%- set color="#268bd2" -%}
{%- endif -%}
<fc={{color}}>{{cpu_times.non_idle | round(precision=1)}}%</fc>\
"""
interval = 5

[ blocks.memory ]
kind = "interval"
command = "awk"
args = [
    "/MemTotal:/{total=$2}/MemAvailable:/{avail=$2}END{printf \"%.01f\", 100 * (1 - avail/total)}",
    "/proc/meminfo",
    ]
interval = 5
template = """<fn=1></fn>
{%- if output | int < 20 -%}
    {%- set color="#586e75" -%}
{%- elif output | int > 50 -%}
    {%- set color="#dc322f" -%}
{%- else -%}
    {%- set color="#268bd2" -%}
{%- endif -%}
<fc={{color}}>{{output}}%</fc>\
"""

[ blocks.jellyfin_status ]
kind = "inotify"
file = "/var/cache/page-status/jellyfin"
template = "{% if contents != \"200\" %}<fc=#cb4b16><fn=2></fn></fc> | {% endif %}"

[ blocks.apt_status ]
kind = "inotify"
file = "/var/cache/page-status/apt"
template = "{% if contents != \"200\" %}<fc=#cb4b16><fn=2></fn></fc> | {% endif %}"

[ blocks.local_mail ]
kind = "inotify"
file = "/var/mail/julian"
template = "<fn=2></fn> {% if contents %}<fc=#b48900><fn=2></fn></fc>{% else %}<fc=#268bd2>✓</fc>{% endif %}"

[ blocks.gmail ]
kind = "inotify"
file = "/home/julian/.cache/gmailcount/jandrews271@gmail.com"
template = """
{%- set count = contents | int(default=-1) -%}
{%- if count > 0 -%}
    {%- set color="#2aa198" -%}
{%- elif count == 0 -%}
    {%- set color="#586e75" -%}
{%- else -%}
    {%- set color="#dc322f" -%}
{%- endif -%}
<action=`xdg-open https://mail.google.com`><fc={{color}}><fn=2></fn> {{ contents | trim -}}</fc></action>\
"""

[ blocks.volume ]
kind = "pulse-volume"
template = """\
{%- if muted -%}
    {%- set icon="<fn=2></fn>" -%}
{%- else -%}
    {%- set icon="<fn=2></fn>" -%}
{%- endif -%}
{%- if muted -%}
    {%- set color="#DC322F" -%}
{%- elif volume <= 35 -%}
    {%- set color="#586e75" -%}
{%- elif volume > 100 -%}
    {%- set color="#b58900" -%}
{%- else -%}
    {%- set color="#268bd2" -%}
{%- endif -%}
<action=`pactl set-sink-mute "{{sink_name}}" toggle` button=2>\
<action=`pactl set-sink-volume "{{sink_name}}" -5%` button=1>\
<action=`pactl set-sink-volume "{{sink_name}}" +5%` button=3>\
<action=`pactl set-sink-volume "{{sink_name}}" -1%` button=5>\
<action=`pactl set-sink-volume "{{sink_name}}" +1%` button=4>\
<fc={{color}}>{{icon}} {{volume}}</fc>%\
</action></action></action></action></action>\
"""

[ blocks.ethernet ]
kind = "network"
device = "enp89s0"
template = """
{%- if operstate == "up" -%}
    <fc=#268bd2><fn=2></fn></fc>
{%- elif operstate == "down" -%}
    <fc=#dc322f><fn=2></fn></fc>
{%- else -%}
    <fc=#268bd2><fn=2>{{device}} {{operstate}}</fn></fc>
{%- endif -%}
"""

[ blocks.wireless ]
kind = "network"
device = "wlo1"
template = "{% if operstate == \"up\" %}<fc=#6c71c4><fn=2></fn></fc> {{essid}} | {% endif %}"
