" Remap leader key to space
" This has to happen before any keybindings that use leader.
noremap <space> <nop>
let mapleader = "\<space>"

" Clear trailing whitespace on save
autocmd BufWritePre * :%s/\s\+$//e

source $HOME/.vim/general.vim
source $HOME/.vim/plugins.vim
source $HOME/.vim/keybindings.vim
source $HOME/.vim/statusline.vim
