[Service]
LoadCredentialEncrypted=fastmail-app-password:/home/julian/.config/credstore/fastmail-app-password.cred
LoadCredentialEncrypted=calendar-sync-client-secret:/home/julian/.config/credstore/calendar-sync-client-secret.cred
