[Service]
LoadCredentialEncrypted=fastmail-app-password:fastmail-app-password.cred
LoadCredentialEncrypted=calendar-sync-client-secret:calendar-sync-client-secret.cred
LoadCredentialEncrypted=calendar-sync-diana-ical-address:calendar-sync-diana-ical-address.cred
