set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
" call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" manually installed bundles
Plugin 'Valloric/YouCompleteMe'
Plugin 'wincent/command-t'
Plugin 'mileszs/ack.vim'
Plugin 'hynek/vim-python-pep8-indent'
Plugin 'tpope/vim-fugitive'
Plugin 'bling/vim-airline'
Plugin 'scrooloose/syntastic'

" All of your Plugins must be added before the following line
call vundle#end()            " required

filetype plugin indent on    " required

syntax on
set expandtab
set softtabstop=2 shiftwidth=2
set number
set background=dark
set clipboard^=unnamed
set backspace=2
set t_Co=256
set laststatus=2
set wildignore+=*.pyc
set mouse=a
set hlsearch
set cursorline
set wildmenu
hi CursorLine term=NONE cterm=NONE ctermbg=234

" Ack config
if executable('ag')
  let g:ackprg = 'ag --vimgrep'
endif

" Airline config
let g:airline_right_sep = '◀'
let g:airline_left_sep = '▶'

" Syntastic config
let g:syntastic_aggregate_errors = 1
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_enable_signs = 0
let g:syntastic_python_checkers = ['python', 'flake8']
let g:syntastic_javascript_checkers = ['eslint']
hi SyntasticError ctermbg=118 ctermfg=0

" CommandT config
let g:CommandTFileScanner='find'

" Clear trailing whitespace in .py files on save
autocmd BufWritePre *.py :%s/\s\+$//e

" Clear trailing whitespace with <F12>
nnoremap <silent> <F12> :%s/\s\+$//e<cr>

" Toggle search highlighting on/off
nnoremap <silent> <Leader>/ :let @/ = ""<bar>SyntasticReset<cr>

" Cycle through location list
nnoremap <silent> <Tab> :try<bar>lnext<bar>catch /^Vim\%((\a\+)\)\=:E\%(553\<bar>42\):/<bar>lfirst<bar>catch /^Vim\%((\a\+)\)\=:E776/<bar>endtry<cr>
nnoremap <silent> <S-Tab> :try<bar>lprevious<bar>catch /^Vim\%((\a\+)\)\=:E\%(553\<bar>42\):/<bar>llast<bar>catch /^Vim\%((\a\+)\)\=:E776/<bar>endtry<cr>
